# Generated by Django 2.2.17 on 2021-01-25 22:48
# Heavily edited manually

from django.db import migrations, models
import django.db.models.deletion
from care.transaction.fields import WeightedManyToManyField


def migrate_to_sharethrough(model, through):
    def migrate_from_auto_m2m(apps, schema_editor):
        Transaction = apps.get_model("transaction", model)
        TransactionConsumer = apps.get_model("transaction", through)

        for transaction in Transaction.objects.all():
            linked_users = transaction.consumers.all()
            tot_weight = linked_users.count()
            transaction.total_weight = tot_weight
            for user in linked_users:
                x_entry = TransactionConsumer(
                    transaction=transaction,
                    consumer=user,
                    share_weight=1,
                )
                x_entry.save()
            transaction.save()

    def migrate_back_to_auto_m2m(apps, schema_editor):
        TransactionConsumer = apps.get_model("transaction", through)

        for x_entry in TransactionConsumer.objects.all():
            transaction = x_entry.transaction
            transaction.consumers.add(x_entry.consumer)

    return migrate_from_auto_m2m, migrate_back_to_auto_m2m


migrate_transaction_forth, migrate_transaction_back = migrate_to_sharethrough(
    "Transaction", "TransactionConsumer"
)

migrate_transactionrec_forth, migrate_transactionrec_back = migrate_to_sharethrough(
    "TransactionRecurring", "TransactionRecurringConsumer"
)


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
        ("transaction", "0005_add_last_modified"),
    ]

    operations = [
        # ========== Create new model TransactionConsumer
        migrations.CreateModel(
            name="TransactionConsumer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_weight",
                    models.DecimalField(
                        decimal_places=4,
                        help_text='Proportion of this transaction, out of "total weight", that the person owes.',
                        max_digits=6,
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_detailed",
                        to="userprofile.UserProfile",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumers_detailed",
                        to="transaction.Transaction",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="transactionconsumer",
            unique_together={("transaction", "consumer")},
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_weight",
            field=models.DecimalField(
                decimal_places=4,
                help_text='Sum of the "share weights" of all the people owing part of this share',
                max_digits=8,
                editable=False,
                null=True,
            ),
        ),
        # ========== Create new model TransactionRecurringConsumer
        migrations.CreateModel(
            name="TransactionRecurringConsumer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_weight",
                    models.DecimalField(
                        decimal_places=4,
                        help_text='Proportion of this transaction, out of "total weight", that the person owes.',
                        max_digits=6,
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_rec_detailed",
                        to="userprofile.UserProfile",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumers_detailed",
                        to="transaction.TransactionRecurring",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="transactionrecurringconsumer",
            unique_together={("transaction", "consumer")},
        ),
        migrations.AddField(
            model_name="transactionrecurring",
            name="total_weight",
            field=models.DecimalField(
                decimal_places=4,
                editable=False,
                help_text='Sum of the "share weights" of all the people owing part of this share',
                max_digits=8,
                null=True,
            ),
            preserve_default=False,
        ),
        # ========== Migrate data from the old, automatic m2m table
        migrations.RunPython(migrate_transaction_forth, migrate_transaction_back),
        migrations.RunPython(migrate_transactionrec_forth, migrate_transactionrec_back),
        # ========== Delete the old auto M2M
        migrations.RemoveField(
            model_name="transaction",
            name="consumers",
        ),
        migrations.RemoveField(
            model_name="transactionrecurring",
            name="consumers",
        ),
        # ========== Add new M2M with through
        migrations.AddField(
            model_name="transaction",
            name="consumers",
            field=WeightedManyToManyField(
                related_name="consumers",
                through="transaction.TransactionConsumer",
                to="userprofile.UserProfile",
                weight_field="share_weight",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_weight",
            field=models.DecimalField(
                decimal_places=4,
                help_text='Sum of the "share weights" of all the people owing part of this share',
                max_digits=8,
                editable=False,
                null=False,
            ),
        ),
        migrations.AddField(
            model_name="transactionrecurring",
            name="consumers",
            field=WeightedManyToManyField(
                related_name="rec_consumers",
                through="transaction.TransactionRecurringConsumer",
                to="userprofile.UserProfile",
                weight_field="share_weight",
            ),
        ),
        migrations.AlterField(
            model_name="transactionrecurring",
            name="total_weight",
            field=models.DecimalField(
                decimal_places=4,
                help_text='Sum of the "share weights" of all the people owing part of this share',
                max_digits=8,
                editable=False,
                null=False,
            ),
        ),
    ]
